---
title: "Mattia Piazzon - Esercizio 1"
output:
  html_document: 
    df_print: paged
    toc: true
    toc_float: true
    number_sections: true
---

# Quiz 1
Dati $X_1, X_2, X_3$ con $X \sim Pois(\theta)$

E gli stimatori:
$T_1 = \frac{2X_1 + X_2/2 + X_3}{5}, \quad T_2 = \frac{X_1 + 2X_2 + 3X_3}{4}$

## Quesito 1: distorsione (distorta)
$$
E(T_1) = \frac{7}{10} \theta
$$

$$
Bias(T_1) = E(T_1)-E(X) = -\frac{3}{10} \theta
$$

Dato che $Bias(T_1) \neq 0, T_1$ è distorto

$$
E(T_2) = \frac3 2 \theta
$$

$$
Bias(T_2) = E(T_2)-E(X) = \frac\theta2
$$

Dato che $Bias(T_2) \neq 0, \quad T_2$ è distorto

## Quesito 2: varianza
$$
Var(T_1) = \frac{21}{100}\theta \\
Var(T_2) = \frac{14}{16}\theta
$$

## Quesito 3: preferenza di stimatore
$$
MSE(T_1) = Bias(T_1)^2 + Var(T_1) = \frac{9}{100}\theta^2 + \frac{21}{100}\theta \\

MSE(T_2) = Bias(T_2)^2 + Var(T_2) = \frac{1}{4}\theta^2 + \frac{7}{8}\theta \\

MSE(T_1) - MSE(T_2) = -\frac{16}{100}\theta^2 - \frac{80.5}{100}\theta \\
$$

Dato che $MSE(T_1) < MSE(T_2), \quad T_1$ è preferibile


# Quiz 2

Dati $X_1 ... X_n$ con
$$
X \sim
\begin{cases}
\frac12, & \text{se }x = -1,\\
\frac{1-\theta}2, & \text{se }x = 0,\\
\frac\theta2, & \text{se }x = 1.\\
\end{cases}
$$
con $\theta \in [0,1]$.

E lo stimatore $T = 2\bar{X} + 1$


## Quesito 1: distorsione (non distorto)
$$
E(\bar{X}) = E(X) = \frac{\theta - 1}2 \\
E(T) = 2E(\bar{X}) + 1 = \theta \\
Bias(T) = E(T)-E(X) = 0
$$

Dato che $Bias(T_1) = 0, T$ è non distorto.

## Quesito 2: Errore standard
$$
E(X^2) = \frac{\theta + 1}2 \\
Var(\bar{X}) = \frac1n Var(X) = \frac1n \big(E(X^2) - E(X)^2 \big) = \frac1n \frac{-\theta^2 + 4\theta + 1}4 \\
SE(T) = \sqrt{Var(T)} = \sqrt{4Var(\bar{X})} = \sqrt{\frac{-\theta^2 + 4\theta + 1}{n}}
$$

## Quesito 3: Consistenza

T è consistente poiche $Bias(T) = 0$ e $Var(T) \to 0$ per $n \to \infty$

# Quiz 3
Dati $X_1 ... X_n$ con $X \sim 2\theta^2x^{-3}$ con $x \ge \theta$ e $\theta > 0$
E lo stimatore $T = \bar{X}/2$

## Quesito 1: distorsione (non distorto)
$$
E(T) = \frac12E(\bar{X}) = \frac12 \int_{\theta}^{\infty} 2\theta^2x^{-2}dx = \theta \\
Bias(T) = E(T)-E(X) = 0
$$

Dato che $Bias(T) = 0, T$ è non distorto

## Quesito 2: Errore standard
Dato che
$$
E(X^2) = \int_{\theta}^{\infty} 2\theta^2x^{-1}dx = \infty
$$
la varianza di T non esiste e quindi $SE(T) = \infty$

## Quesito 3: Consistenza
T non è consistente poiche $SE(T) = \infty$


# Quiz 4

Dati $X_1 ... X_n$ con $X \sim \frac{2(\theta - x)}\theta^2$ con $0 < x < \theta$ e $\theta > 0$
e lo stimatore $T = 3\bar{X}$

## Quesito 1: distorsione (non distorto)
$$
E(T) = 3E(\bar{X}) = 3E(X) = 3\int_{0}^{\theta} x\frac{2(\theta - x)}{\theta^2}dx = 3 \big(\frac13 \theta\big) = \theta \\
Bias(T) = E(T)-E(X) = 0
$$

Dato che $Bias(T) = 0, T$ è non distorto

## Quesito 2: Errore quadratico medio

Dato che $Bias(T) = 0, MSE(T) = Var(T) = \frac9nVar(X)$

$$
E(X^2) = \int_{0}^{\theta} x^2\frac{2(\theta - x)}{\theta^2}dx = \frac16 \theta^2 \\
Var(X) = E(X^2) - E(X)^2 = \frac16 \theta^2 - \frac19 \theta^2 = \frac{1}{18}\theta^2 \\
MSE(T) = \frac9nVar(X) = \frac{1}{2n}\theta^2
$$

## Quesito 3: Consistenza

T è consistente poiche $Bias(T) = 0$ e $Var(T) \to 0$ per $n \to \infty$




# Quiz 5

Dati $X_1 ... X_n$ un campione casuale semplice da una variabile casuale di Poisson con parametro $\theta > 0$. Si considerino i seguenti due stimatori di θ:
$$
\hat \theta_1 = \frac{1}{4}X_1 + \frac{3}{4}X_n \\
\hat \theta_2 = \frac{1}{n-3} \sum_{i=1}^n X_i, \quad n >= 4\\
$$
Calcolare la distorsione dei due stimatori, l'errore standard e dire quale dei due sia preferibile quando $\theta = 5$.


## Quesito 1: distorsione

Calcolo valore atteso e bias:
$$
E(\hat \theta_1) = \frac{1}{4}E(X_1) + \frac{3}{4}E(X_n) = \frac{1}{4}\theta + \frac{3}{4}\theta = \theta \\
Bias(\hat \theta_1) = E(\hat \theta_1) - \theta = 0\\
$$
$$
E(\hat \theta_2) = \frac{1}{n-3}E\big(\sum_{i=1}^n X_i\big) = \frac{1}{n-3}n\theta \\
Bias(\hat \theta_2) = E(\hat \theta_2) - \theta = \frac{1}{n-3}n\theta - \theta = \frac{3\theta}{n-3}\\
$$
Quindi $\hat \theta_1$ è non distorto e $\hat \theta_2$ è non distorto per $n \to \infty$

## Quesito 2: Errore standard
Trovo prima la varianza:
$$
Var(\hat \theta_1) = \frac{1}{16}Var(X_1) + \frac{9}{16}Var(X_n) = \frac{1}{16}\theta + \frac{9}{16}\theta = \frac{5}{8}\theta \\
Var(\hat \theta_2) = \frac{1}{(n-3)^2}Var\big(\sum_{i=1}^n X_i\big) = \frac{1}{(n-3)^2}n\theta = \frac{n\theta}{(n-3)^2}\\
$$
Trovo ora lo Standard Error:
$$
SE(\hat \theta_1) = \sqrt{Var(\hat \theta_1)} = \sqrt{\frac{5}{8}\theta} \\
SE(\hat \theta_2) = \sqrt{Var(\hat \theta_2)} = \sqrt{\frac{n\theta}{(n-3)^2}}\\
$$
Per poter confrontare i due stimatori è necessario calcolare il loro MSE:
$$
MSE(\hat \theta_1) = Var(\hat \theta_1) = \frac{5}{8}\theta \\
MSE(\hat \theta_2) = Var(\hat \theta_2) + Bias(\hat \theta_2)^2 = \frac{n\theta}{(n-3)^2} + \frac{9\theta^2}{(n-3)^2} = \frac{n\theta + 9\theta^2}{(n-3)^2} \\
$$
## Quesito 3: Preferenza di stimatore

Per poterli confrontare devo considerare due casi, n non finito e n finito:

Per $n$ che diverge è preferibile, qualunque sia $\theta$, il secondo stimatore perché è consistente a differenza del primo stimatore.

Per $n$ finito, la scelta dello stimatore dipende dal confronto degli errori quadratici medi. Possiamo calcolare il valore di $n$ per cui è preferibile il primo stimatore risolvendo una equazione del secondo ordine oppure valutare gli errori quadratici medi per enumerazione:
```{r}
theta <- 5
MSE1 <- (5)/(8) * theta
MSE1
MSE2 <- function(n) (9 * theta ^ 2 + n * theta) / ((n - 3) ^ 2)
MSE2(4 : 20)
```
Eseguendo i calcoli ottengo che MSE1 = 3.125, devo quindi trovare per quali $n$ MSE2 è minore di 3.125. Eseguendo i calcoli ottengo che per $n \geq 13$ il secondo stimatore è preferibile, mentre fino ad $n=12$ il primo stimatore è preferibile.


# Quiz 6

Sia $X_1, \ldots, X_{221}$ un campione casuale semplice da una variabile casuale con funzione di densità

$$f(x; \theta) = 19x^{18}\theta^{-19}, \quad \text{per} \; 0 < x < \theta \; \text{e} \; \theta >0$$

Si consideri lo stimatore $\hat{\theta}=\bar{X}$:

1. Si calcoli la distorsione di $\hat{\theta}$ [3 punti];
2. Si calcoli l’errore standard di $\hat{\theta}$ [3 punti];
3. Si valuti la consistenza di $\hat{\theta}$ [2 punti].

Istruzioni:

1. riportare il valore atteso e la distorsione dello stimatore;
2. riportare l’errore standard dello stimatore;
3. riportare i conti necessari per rispondere al quesito.

## Punto 1

1. Calcolo il valore atteso di $X_i$:
$$E[X_i] = \int_0^\theta 19x^{19}\theta^{-19} \, dx = 19\theta^{-19} \frac{x^{20}}{20} \bigg\rvert_0^\theta = \frac{19}{20}\theta$$
Ora calcolo il valore atteso di $\bar{X}$:
$$E[\bar{X}] = E\left[\frac{1}{n}\sum_{i=1}^n X_i\right] = \frac{1}{n}\sum_{i=1}^n E[X_i] = \frac{1}{n}nE[X_i] = E[X_i] = \frac{19}{20}\theta$$
La distorsione di $\hat{\theta}$ è quindi:
$$\text{Bias}(\hat{\theta}) = E[\hat{\theta}] - \theta = \frac{19}{20}\theta - \theta = -\frac{1}{20}\theta$$

## Punto 2

2. Prima calcolo $E[X_i^2]$:
$$E[X_i^2] = \int_0^\theta 19x^{19}\theta^{-19} \, dx = 19\theta^{-19} \frac{x^{21}}{21} \bigg\rvert_0^\theta = \frac{19}{21}\theta^2$$
Ora calcolo la varianza di $X_i$:
$$\text{Var}(X_i)=E[X_i^2]-E[X_i]^2=\frac{19}{21}\theta^2-\left(\frac{19}{20}\theta\right)^2=\left(\frac{19}{21}-\left(\frac{19}{20}\right)^2\right)\theta^2$$
L'errore standard di $\hat{\theta}$ è quindi:
$$\text{SE}(\hat{\theta}) = \sqrt{\frac{1}{n^2}\left(n\text{Var}(X_i)\right)}= \sqrt{\frac{\text{Var}(X_i)}{n}} = \sqrt{\frac{\left(\frac{19}{21}-\left(\frac{19}{20}\right)^2\right)\theta^2}{n}}$$

## Punto 3

3. Affinché $\hat{\theta}$ sia consistente, deve valere che $\text{Bias}(\hat{\theta}) \to 0$ e $\text{SE}(\hat{\theta}) \to 0$ per $n \to \infty$. Però abbiamo visto che $\text{Bias}(\hat{\theta}) = -\frac{1}{20}\theta \neq 0$, quindi $\hat{\theta}$ non è consistente.



# Quiz 7

Sia $X_1,…,X_n$ un campione casuale semplice da una variabile casuale di Poisson di parametro θ
. Si considerano i seguenti due stimatori di θ:
$$
\hat \theta_1 = \frac{(n/4)X_1 + (3n/4)X_n}{n} \quad \hat \theta_2 = \frac{1}{n-2}\sum_{i=1}^n X_i \quad n \geq 3
$$

# Punto 1

Calcolo il valoro atteso dei due stimatori:
$$
E(\hat \theta_1) = \theta \\

E(\hat \theta_2) = \frac{n\theta}{n -2} \\

$$

Calcolo ora il loro Bias:
$$
Bias(\hat \theta_1) = E(\hat \theta_1) - \theta = 0 \\
Bias(\hat \theta_2) = E(\hat \theta_2) - \theta = \frac{n\theta}{n -2} - \theta = \frac{2\theta}{n -2} \\
$$

Quindi lo stimatore $\hat \theta_1$ è non distorto, mentre $\hat \theta_2$ è non distorto per n che tende a infinito.

# Punto 2

Per calcolare il loro errore quadratico medio necessito della loro varianza:
$$
Var(\hat \theta_1) = \frac{n^2}{16n^2}Var(X_1) + \frac{9n^2}{16n^2}Var(X_n) = \frac{1}{16}\theta + \frac{9}{16}\theta = \frac{5}{8}\theta \\

Var(\hat \theta_2) = \frac{1}{(n-2)^2}Var\left(\sum_{i=1}^n X_i\right) = \frac{1}{(n-2)^2}n\theta = \frac{n\theta}{(n-2)^2} \\
$$

Calcolo i loro MSE:
$$
MSE(\hat \theta_1) = Var(\hat \theta_1) = \frac{5}{8}\theta \\

MSE(\hat \theta_2) = Var(\hat \theta_2) + Bias(\hat \theta_2)^2 = \frac{n\theta}{(n-2)^2} + \left(\frac{2\theta}{n -2}\right)^2 = \frac{n\theta}{(n-2)^2} + \frac{4\theta^2}{(n -2)^2} = \frac{n\theta + 4\theta^2}{(n-2)^2} \\
$$
# Punto 3

Per valutare la loro consistenza devo valutare due casi, n finito e n non finito.

Per n non finito, qualunque sia $\theta$ è preferibile il secondo stimatore perché è consistente dato che la varianza tende a 0 per n che tende a infinito, mentre il primo stimatore non è consistente.

Per n finito devo valutare i loro MSE per poterli confrontare.
























